#!/bin/bash
echo "🚀 퍼티스트 앱 실행 중..."
echo ""
echo "📱 Expo Go 앱에서 다음 방법으로 연결하세요:"
echo ""
echo "방법 1: URL 직접 입력"
echo "========================"
echo "exp://192.168.1.1:8081"
echo "(실제 IP 주소로 변경 필요)"
echo ""
echo "방법 2: 웹 브라우저"
echo "========================"
echo "http://localhost:8081"
echo ""
echo "방법 3: QR 코드 생성 사이트"
echo "========================"
echo "1. https://www.qr-code-generator.com/ 접속"
echo "2. 'exp://YOUR_IP:8081' 입력"
echo "3. QR 코드 생성 후 스캔"
echo ""
echo "📌 네트워크 IP 확인:"
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "IP: " $2}'
echo ""
npx expo start